import { Appointment, Clinician, QueueMetrics } from "../types/appointment";

export const mockClinicians: Clinician[] = [
  { id: "1", name: "Dr. Sarah Chen", specialty: "General Practice", availableSlots: 8 },
  { id: "2", name: "Dr. Michael Roberts", specialty: "Cardiology", availableSlots: 5 },
  { id: "3", name: "Dr. Emily Rodriguez", specialty: "Pediatrics", availableSlots: 12 },
  { id: "4", name: "Dr. James Thompson", specialty: "Orthopedics", availableSlots: 6 },
];

export const mockAppointments: Appointment[] = [
  {
    id: "1",
    patientId: "P001",
    displayLabel: "J. Smith #0421",
    appointmentNumber: "0421",
    status: "IN_PROGRESS",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 25 * 60000),
    startedAt: new Date(Date.now() - 5 * 60000),
    estimatedWaitMinutes: 0,
    clinicianId: "1",
    clinicianName: "Dr. Sarah Chen",
  },
  {
    id: "2",
    patientId: "P002",
    displayLabel: "M. Johnson #0422",
    appointmentNumber: "0422",
    status: "IN_PROGRESS",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 30 * 60000),
    startedAt: new Date(Date.now() - 8 * 60000),
    estimatedWaitMinutes: 0,
    clinicianId: "2",
    clinicianName: "Dr. Michael Roberts",
  },
  {
    id: "3",
    patientId: "P003",
    displayLabel: "A. Williams #0423",
    appointmentNumber: "0423",
    status: "READY",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 20 * 60000),
    estimatedWaitMinutes: 2,
    clinicianId: "1",
    clinicianName: "Dr. Sarah Chen",
  },
  {
    id: "4",
    patientId: "P004",
    displayLabel: "R. Davis #0424",
    appointmentNumber: "0424",
    status: "READY",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 18 * 60000),
    estimatedWaitMinutes: 3,
    clinicianId: "3",
    clinicianName: "Dr. Emily Rodriguez",
  },
  {
    id: "5",
    patientId: "P005",
    displayLabel: "L. Martinez #0425",
    appointmentNumber: "0425",
    status: "QUEUED",
    queuePosition: 1,
    createdAt: new Date(Date.now() - 10 * 60000),
    estimatedWaitMinutes: 15,
    clinicianId: "4",
    clinicianName: "Dr. James Thompson",
  },
  {
    id: "6",
    patientId: "P006",
    displayLabel: "K. Brown #0426",
    appointmentNumber: "0426",
    status: "QUEUED",
    queuePosition: 2,
    createdAt: new Date(Date.now() - 8 * 60000),
    estimatedWaitMinutes: 20,
    clinicianId: "1",
    clinicianName: "Dr. Sarah Chen",
  },
  {
    id: "7",
    patientId: "P007",
    displayLabel: "S. Anderson #0427",
    appointmentNumber: "0427",
    status: "QUEUED",
    queuePosition: 3,
    createdAt: new Date(Date.now() - 5 * 60000),
    estimatedWaitMinutes: 25,
    clinicianId: "2",
    clinicianName: "Dr. Michael Roberts",
  },
  {
    id: "8",
    patientId: "P008",
    displayLabel: "T. Garcia #0428",
    appointmentNumber: "0428",
    status: "QUEUED",
    queuePosition: 4,
    createdAt: new Date(Date.now() - 3 * 60000),
    estimatedWaitMinutes: 30,
    clinicianId: "3",
    clinicianName: "Dr. Emily Rodriguez",
  },
  {
    id: "9",
    patientId: "P009",
    displayLabel: "P. Wilson #0429",
    appointmentNumber: "0429",
    status: "COMPLETED",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 90 * 60000),
    startedAt: new Date(Date.now() - 75 * 60000),
    completedAt: new Date(Date.now() - 60 * 60000),
    estimatedWaitMinutes: 0,
    clinicianId: "4",
    clinicianName: "Dr. James Thompson",
  },
  {
    id: "10",
    patientId: "P010",
    displayLabel: "N. Lee #0430",
    appointmentNumber: "0430",
    status: "COMPLETED",
    queuePosition: 0,
    createdAt: new Date(Date.now() - 120 * 60000),
    startedAt: new Date(Date.now() - 105 * 60000),
    completedAt: new Date(Date.now() - 90 * 60000),
    estimatedWaitMinutes: 0,
    clinicianId: "1",
    clinicianName: "Dr. Sarah Chen",
  },
];

export const mockMetrics: QueueMetrics = {
  currentQueueLength: 3,
  avgWaitTime: 22,
  throughputToday: 24,
  noShowRate: 5.2,
};